### ISSUE TITLE
update

### ISSUE THREAD

**Issue by mikeemike7** [pixelschrubber/toc#1]
hi, will there be an update for typo3 v10.4? Yours, mikee

**Comment by pixelschrubber** [comment]
Hi @mikeemike7 - thanks for the interest - did you try this release? https://github.com/pixelschrubber/toc/releases/tag/0.8.0

**Comment by mikeemike7** [comment]
hi Ulf Mayer, I'll try this one. Thanks a lot for this great extension! Sincerley, Mikee
