### ISSUE TITLE
Annotation error

### ISSUE THREAD

**Issue by Hobokens** [pixelschrubber/toc#2]
Hi,
I tried toc v0.8 and got the following error 
`
[Semantical Error] The annotation "@inject" in property ONEANDONE\Toc\Controller\TOCController::$tocRepository was never imported. Did you maybe forget to add a "use" statement for this annotation?`

TYPO3 10.4.21

**Comment by helmut-winkelbach** [comment]
The same here.
;)

**Comment by pixelschrubber** [comment]
Thanks for letting me know, will look into it

**Comment by Hobokens** [comment]
Hi,
do you plan to fix this issue?
Regards
Hobokens

**Comment by pixelschrubber** [comment]
@Hobokens - Sorry, currently a different focus and I have to set up a typo3 dev environment every time I do updates on this extension. Since you got a vivid interest in it, would you like to take over the ownership of the extension?

**Comment by Hobokens** [comment]
Thank you for your takeover offer. Since I am only an integrator, my PHP knowledge is unfortunately too low for this.

**Comment by pixelschrubber** [comment]
Should be fixed with latest release?

**Comment by Hobokens** [comment]
It's fixed now, thanks a lot!
